export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_RES_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=9.9312328&lng=76.26730409999999&restaurantId=";


export const ALL_RESTAURANTS_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=9.9312328&lng=76.26730409999999&page_type=DESKTOP_WEB_LISTING"




// export const restaurantList = [
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "251885",
//       name: "TASTE OF PUNJAB BY AHC",
//       uuid: "a461f116-eaf3-4a78-832a-a5ec91eae3a3",
//       city: "13",
//       area: "Perumanoor",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "vmdl0pd1jzn4davtmjlt",
//       cuisines: ["Indian"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 36,
//       minDeliveryTime: 36,
//       maxDeliveryTime: 36,
//       slaString: "36 MINS",
//       lastMileTravel: 3.9000000953674316,
//       slugs: {
//         restaurant: "taste-of-punjab-by-ahc-mg-road-mg-road",
//         city: "kochi",
//       },
//       cityState: "13",
//       address:
//         "Tate of Punjab, 60/3448 A4 Puliyilathu building Perumanoor Kochin - 682015",
//       locality: "Puliyilathu",
//       parentId: 201683,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "25% off",
//         shortDescriptionList: [
//           {
//             meta: "25% off | Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "25% off up to ₹65 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "25% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "25% off up to ₹65 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6530428~p=1~eid=00000187-a413-d842-0373-7e9d00e7011e",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "3.9 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "251885",
//         deliveryTime: 36,
//         minDeliveryTime: 36,
//         maxDeliveryTime: 36,
//         lastMileTravel: 3.9000000953674316,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.3",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "299451",
//       name: "The Salt Restaurant",
//       uuid: "e8b67766-db29-4fd5-ac72-f9056bef0b85",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "em9fdvyzojbku52rcu5q",
//       cuisines: ["Beverages", "Chinese", "Fast Food"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 20,
//       minDeliveryTime: 20,
//       maxDeliveryTime: 20,
//       slaString: "20 MINS",
//       lastMileTravel: 0.800000011920929,
//       slugs: {
//         restaurant: "the-salt-restaurant-fort-kochi-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "11/353773538,3539 MARINA MALL THOPPUMPADY, Ernakulam,  -682005",
//       locality: "Marina Mall",
//       parentId: 213520,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "Flat ₹125 off",
//         shortDescriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "₹125 OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "299451",
//         deliveryTime: 20,
//         minDeliveryTime: 20,
//         maxDeliveryTime: 20,
//         lastMileTravel: 0.800000011920929,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.9",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "218603",
//       name: "MR. SHAWARMA",
//       uuid: "d03625b9-9847-4590-b99f-9d0377f31273",
//       city: "13",
//       area: "Palluruthy",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "gxilj3x6uvyegb3ntupq",
//       cuisines: ["Arabian"],
//       tags: [],
//       costForTwo: 19000,
//       costForTwoString: "₹190 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 1.2999999523162842,
//       slugs: {
//         restaurant: "mr.shawarma-fort-kochi-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "Palluruthy PO Ernakulam",
//       locality: "",
//       parentId: 9992,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "10% off",
//         shortDescriptionList: [
//           {
//             meta: "10% off | Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off up to ₹40 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "10% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off up to ₹40 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "218603",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 1.2999999523162842,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "376052",
//       name: "NIC Ice Creams",
//       uuid: "baa984bd-6648-43d1-849d-3df3cd722126",
//       city: "13",
//       area: "Panampilly Nagar",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "91d6dda411b108965541c16ac1cfe2bc",
//       cuisines: ["Ice Cream", "Desserts"],
//       tags: [],
//       costForTwo: 12000,
//       costForTwoString: "₹120 FOR TWO",
//       deliveryTime: 31,
//       minDeliveryTime: 31,
//       maxDeliveryTime: 31,
//       slaString: "31 MINS",
//       lastMileTravel: 5.5,
//       slugs: {
//         restaurant: "nic-natural-ice-creams-parambithara-road-panampilly-nagar",
//         city: "kochi",
//       },
//       cityState: "13",
//       address:
//         "Shop no 55/63-B (South-West Portion) Parambithara Road, Panampilly Nagar, Cochin, Kerala-682036, Ernakulam, Kerala-682036",
//       locality: "Parambithara Road",
//       parentId: 6249,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 4500,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 4500,
//         message: "",
//         title: "Delivery Charge",
//         amount: "4500",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6528017~p=4~eid=00000187-a413-d842-0373-7e9e00e70454",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "376052",
//         deliveryTime: 31,
//         minDeliveryTime: 31,
//         maxDeliveryTime: 31,
//         lastMileTravel: 5.5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.6",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "64001",
//       name: "Chicking",
//       uuid: "4eadd6e1-6ce2-4fcb-9278-7c822d0e6867",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "5000+ ratings",
//       cloudinaryImageId: "jasm6doxd15mw0ko5auv",
//       cuisines: [
//         "Snacks",
//         "Grill",
//         "Fast Food",
//         "American",
//         "Pizzas",
//         "Mexican",
//         "Beverages",
//       ],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 26,
//       minDeliveryTime: 26,
//       maxDeliveryTime: 26,
//       slaString: "26 MINS",
//       lastMileTravel: 1.100000023841858,
//       slugs: {
//         restaurant: "chicking-fried-chicken-thopumpady-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "L. G. Tower, P T Jacob Road, Thopumpady, Koch",
//       locality: "P T Jacob Road",
//       parentId: 251,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "Flat ₹125 off",
//         shortDescriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "₹125 OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.1 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "64001",
//         deliveryTime: 26,
//         minDeliveryTime: 26,
//         maxDeliveryTime: 26,
//         lastMileTravel: 1.100000023841858,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 5000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "155350",
//       name: "Khana Peena Pure Veg Restaurant",
//       uuid: "201d26b7-c9f0-4631-b1a8-ad3e55731a17",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "ekkedcps0ify0fi5swup",
//       cuisines: ["North Indian", "South Indian"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 21,
//       minDeliveryTime: 21,
//       maxDeliveryTime: 21,
//       slaString: "21 MINS",
//       lastMileTravel: 0.20000000298023224,
//       slugs: {
//         restaurant: "khana-peena-pure-veg-restaurant-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "Pyari Junction,Thoppumpady,Kochi",
//       locality: "Pyari Junction",
//       parentId: 20472,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "30% off",
//         shortDescriptionList: [
//           {
//             meta: "30% off | Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "30% off up to ₹75 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "30% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "30% off up to ₹75 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "155350",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         lastMileTravel: 0.20000000298023224,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "53355",
//       name: "Burger King",
//       uuid: "c8d7a06a-112d-44dc-9376-59d06fabe1db",
//       city: "13",
//       area: "Shenoys",
//       totalRatingsString: "10000+ ratings",
//       cloudinaryImageId: "28fb13049b4e55297bb3f703cde63c35",
//       cuisines: ["Burgers", "American"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 61,
//       minDeliveryTime: 61,
//       maxDeliveryTime: 61,
//       slaString: "61 MINS",
//       lastMileTravel: 7.599999904632568,
//       slugs: {
//         restaurant: "burger-king-fifth-floor-centre-square-edapally",
//         city: "kochi",
//       },
//       cityState: "13",
//       address:
//         "Burger King India Private Limited, Unit 502, Fifth Floor, Centre Square, 66 6284 A1, M.G. Road, Ernakulam, Cochin, Kerala 682035",
//       locality: "Mahatma Gandhi Road",
//       parentId: 166,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹120 | Use code STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹120 | Use code STEALDEAL",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 5900,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 5900,
//         message: "",
//         title: "Delivery Charge",
//         amount: "5900",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6524170~p=7~eid=00000187-a413-d842-0373-7e9f00e70701",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "53355",
//         deliveryTime: 61,
//         minDeliveryTime: 61,
//         maxDeliveryTime: 61,
//         lastMileTravel: 7.599999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.3",
//       totalRatings: 10000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "117145",
//       name: "Hotel Salwa",
//       uuid: "2643353f-e735-4f56-87aa-a79e20c28b3f",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "rukcvz0dlcn9e2tohfq5",
//       cuisines: ["Indian", "Biryani"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 16,
//       minDeliveryTime: 16,
//       maxDeliveryTime: 16,
//       slaString: "16 MINS",
//       lastMileTravel: 0.800000011920929,
//       slugs: {
//         restaurant: "hotel-salwa-thopumpady-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "Thoppampady, Thopumpady, Kochi",
//       locality: "Aroor - Thoppumpady Road",
//       parentId: 20578,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "117145",
//         deliveryTime: 16,
//         minDeliveryTime: 16,
//         maxDeliveryTime: 16,
//         lastMileTravel: 0.800000011920929,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.8",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "622386",
//       name: "Juicy",
//       uuid: "8c0f4603-b400-49f6-b1c2-d3d5c03c1ecb",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "20+ ratings",
//       cloudinaryImageId: "ogmvqqyzysnawptm3cpf",
//       cuisines: ["Beverages", "Fast Food", "Snacks"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 18,
//       minDeliveryTime: 18,
//       maxDeliveryTime: 18,
//       slaString: "18 MINS",
//       lastMileTravel: 0.30000001192092896,
//       slugs: {
//         restaurant: "juicy-fort-kochi-fort-kochi",
//         city: "kochi",
//       },
//       cityState: "13",
//       address:
//         "JUICY,11/3161(1),VARAMBATH LANE,PYARI JUNCTION,THOPPUMPADY,COCHIN, Kochi Circle, Ernakulam, Kerala682005",
//       locality: "Pyari Junction",
//       parentId: 20465,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "10% off",
//         shortDescriptionList: [
//           {
//             meta: "10% off | Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off up to ₹40 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "10% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "10% off up to ₹40 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "622386",
//         deliveryTime: 18,
//         minDeliveryTime: 18,
//         maxDeliveryTime: 18,
//         lastMileTravel: 0.30000001192092896,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.4",
//       totalRatings: 20,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "367962",
//       name: "La Pino'z Pizza",
//       uuid: "d0b6a342-84b9-4895-83cf-7c20410e0f9b",
//       city: "13",
//       area: "Elamkulam",
//       totalRatingsString: "5000+ ratings",
//       cloudinaryImageId: "fallovrabd8hftqphizq",
//       cuisines: ["Pizzas", "Italian"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 42,
//       minDeliveryTime: 42,
//       maxDeliveryTime: 42,
//       slaString: "42 MINS",
//       lastMileTravel: 7.099999904632568,
//       slugs: {
//         restaurant: "la-pino'z-pizza-kaloor-kaloor",
//         city: "kochi",
//       },
//       cityState: "13",
//       address:
//         "1st floor MKV building, pillar number 687 MG road, near shehnoys theatre Ernakulam",
//       locality: "Mg Road",
//       parentId: 4961,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "Flat ₹125 off",
//         shortDescriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "₹125 OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
//             discountType: "Flat",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 5900,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 5900,
//         message: "",
//         title: "Delivery Charge",
//         amount: "5900",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=6536240~p=10~eid=00000187-a413-d842-0373-7ea000e70a5d",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "367962",
//         deliveryTime: 42,
//         minDeliveryTime: 42,
//         maxDeliveryTime: 42,
//         lastMileTravel: 7.099999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.2",
//       totalRatings: 5000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "150015",
//       name: "Cake Hut",
//       uuid: "45c86442-6c63-4aac-ac3d-9b465e6f9afc",
//       city: "13",
//       area: "Chullickal",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "wgq46ryba9c9lp95asnh",
//       cuisines: ["Bakery"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 18,
//       minDeliveryTime: 18,
//       maxDeliveryTime: 18,
//       slaString: "18 MINS",
//       lastMileTravel: 0.20000000298023224,
//       slugs: {
//         restaurant: "cake-hut-mg-road-mg-road",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "Parry Junction, Thoppumpady, Kochi, Kerala 682005",
//       locality: "Parry Junction",
//       parentId: 4752,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "20% off",
//         shortDescriptionList: [
//           {
//             meta: "20% off | Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "20% off up to ₹50 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "20% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "20% off up to ₹50 | Use code TRYNEW",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "0.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "150015",
//         deliveryTime: 18,
//         minDeliveryTime: 18,
//         maxDeliveryTime: 18,
//         lastMileTravel: 0.20000000298023224,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.6",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "546364",
//       name: "KFC",
//       uuid: "b522082a-1dcc-4f61-a6ad-483cb700a9b4",
//       city: "13",
//       area: "Thopumpady",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
//       cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
//       tags: [],
//       costForTwo: 40000,
//       costForTwoString: "₹400 FOR TWO",
//       deliveryTime: 26,
//       minDeliveryTime: 26,
//       maxDeliveryTime: 26,
//       slaString: "26 MINS",
//       lastMileTravel: 1.399999976158142,
//       slugs: {
//         restaurant: "kfc-thoppumpaddy-panampilly-nagar",
//         city: "kochi",
//       },
//       cityState: "13",
//       address: "16/844, Nankelil House, Thoppumpady, Kochi",
//       locality: "Nankelil House",
//       parentId: 547,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "40% off",
//         shortDescriptionList: [
//           {
//             meta: "40% off | Use SWIGGYIT",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "40% off up to ₹80 on select items | Use code SWIGGYIT",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "40% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use SWIGGYIT",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "40% off up to ₹80 on select items | Use code SWIGGYIT",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "1.3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "546364",
//         deliveryTime: 26,
//         minDeliveryTime: 26,
//         maxDeliveryTime: 26,
//         lastMileTravel: 1.399999976158142,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
// ];
